name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
    - "v*"
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # TODO make use of build spec and do it
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}   
          repository: vijaysamanuri/password-manager
          tag_with_ref: true
 
      - name: Get the image tag
        id: get_tag
        run: echo "::set-output name=image_tag::${GITHUB_REF##*/}" 
        
      - name: Run vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with: 
          image-ref: 'docker.io/vijaysamanuri/password-manager:${{ steps.get_tag.outputs.image_tag }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          
